FROM golang:1.19 AS builder
ENV CGO_ENABLED 0
WORKDIR /go/src/app
ADD . .
RUN go build -o /ezadmis-httpcat ./cmd/ezadmis-httpcat

FROM alpine:3.16
RUN apk add --no-cache ca-certificates tzdata
COPY --from=builder /ezadmis-httpcat /ezadmis-httpcat
CMD ["/ezadmis-httpcat"]