name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: build
        run: go build -v ./...

      - name: test
        run: go test -v ./...

      - name: dockerhub login
        uses: docker/login-action@v2
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: dockerhub build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: guoyk/ezadmis-install:latest
          file: ./Dockerfile.ezadmis-install